spring:
  datasource:
    username: postgres
    password: Password123.
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #maspari i krijon tabelat prej modelev tani i kqyr scriptet
  sql:
    init:
      mode: always