spring:
  datasource:
    username: postgres
    password: Password123.
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #maspari i krijon tabelat prej modelev tani i kqyr scriptet
  sql:
    init:
      mode: always
  flyway:
   # baseline-on-migrate: true #kur te perdorim flyway , flyway kqyr ku ka me i migrate senet ,mujna me ja ndryshu edhe dataabasen, kur te perdorim me true i bjen qe po du me perdor databazen e njejt
    enabled: false
